### ISSUE TITLE
Modify lind-nacl Compilation Script to Support Both Rustposix and Rawposix

### ISSUE THREAD

**Issue by Yaxuan-w** [Lind-Project/RawPOSIX#12]
Currently, when using RawPOSIX with lind-nacl, we need to manually delete the original safeposix-rust, clone the rawposix repo, and rename it to safeposix-rust. This process is necessary because we use the original lind compilation scripts, and although rawposix has made some modifications to the scripts, it still relies on the original safeposix-rust scripts to avoid potential issues.

To streamline integration with wasm and enhance usability, I propose modifying the lind-nacl compilation script to include an option to compile either lind-nacl-rustposix or lind-nacl-rawposix. This would simplify the workflow and make it more adaptable for future developments.

Let's discuss how best to implement this change.

**Comment by rennergade** [comment]
This seems like a great idea. I'm concerned about versioning since I believe the wasm integration will break some key things that NaCl uses.

**Comment by Yaxuan-w** [comment]
Finished by new Lind-project PR https://github.com/Lind-Project/lind_project/pull/392
