### ISSUE TITLE
Eliminate Interface Directory/Reorganize necessary files

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/RawPOSIX#45]
# Removed Functions Documentation

##### File: `file.rs`: PR #53

- [removefile](#removefile)
- [openfile](#openfile)
- [openmetadata](#openmetadata)
- [pathexists](#pathexists)
- [EmulatedFile Struct](#emulatedfile-struct)
  - [new](#new)
  - [new_metadata](#new_metadata)
  - [close](#close)
  - [shrink](#shrink)
  - [fdatasync](#fdatasync)
  - [fsync](#fsync)
  - [sync_file_range](#sync_file_range)
  - [readat](#readat)
  - [writeat](#writeat)
  - [readfile_to_new_bytes](#readfile_to_new_bytes)
  - [writefile_from_bytes](#writefile_from_bytes)
  - [zerofill_at](#zerofill_at)
  - [as_fd_handle_raw_int](#as_fd_handle_raw_int)
- [EmulatedFileMap Struct](#emulatedfilemap-struct)
  - [new](#new_emulatedfilemap)
  - [write_to_map](#write_to_map)
  - [extend_map](#extend_map)
  - [close_emulatedfilemap](#close_emulatedfilemap)
  - [mapfilenew](#mapfilenew)
- [Test Module](#test-module)
  - [test_path_exists_true](#test_path_exists_true)
  - [test_path_exists_false](#test_path_exists_false)

##### File: `misc.rs`: PR #54 

- [AdvisoryLock Struct](#advisorylock-struct)
  - [new](#new)
  - [lock_ex](#lock_ex)
  - [lock_sh](#lock_sh)
  - [try_lock_ex](#try_lock_ex)
  - [try_lock_sh](#try_lock_sh)
  - [unlock](#unlock)

##### File: `pipe.rs`: PR #55 

- [new_pipe](#new_pipe)
- [EmulatedPipe Struct](#emulatedpipe-struct)
  - [new_with_capacity](#new_with_capacity)
  - [set_eof](#set_eof)
  - [get_write_ref](#get_write_ref)
  - [get_read_ref](#get_read_ref)
  - [incr_ref](#incr_ref)
  - [decr_ref](#decr_ref)
  - [check_select_read](#check_select_read)
  - [check_select_write](#check_select_write)
  - [write_to_pipe](#write_to_pipe)
  - [read_from_pipe](#read_from_pipe)
- [Debug Implementation for EmulatedPipe](#debug-implementation-for-emulatedpipe)

##### File: `types.rs`: PR #56 

- [FSData Struct](#fsdata-struct)
- [get_fdset](#get_fdset)
- [get_statdatastruct](#get_statdatastruct)
- [get_fsdatastruct](#get_fsdatastruct)
- [get_ioctlptrunion](#get_ioctlptrunion)
- [get_ioctl_int](#get_ioctl_int)
- [get_ioctl_char](#get_ioctl_char)
- [pack_dirents](#pack_dirents)
- [get_sockaddr](#get_sockaddr)
- [get_epollevent](#get_epollevent)
- [get_itimerval](#get_itimerval)
- [get_constitimerval](#get_constitimerval)
- [get_sem](#get_sem)
- [get_ifaddrs](#get_ifaddrs)

---

## File: `file.rs`

<h3 id="removefile">removefile</h3>

- **Purpose:**  
  Deletes a file from the filesystem.
- **Details:**  
  Takes a filename as input, checks if the file exists, and removes it.

---

<h3 id="openfile">openfile</h3>

- **Purpose:**  
  Opens a file and creates an `EmulatedFile` object with a specified filesize.
- **Details:**  
  Used to open files for reading and writing, with options for file creation.

---

<h3 id="openmetadata">openmetadata</h3>

- **Purpose:**  
  Opens a file to access its metadata and returns an `EmulatedFile` object.
- **Details:**  
  Retrieves the file size and relevant metadata upon opening.

---

<h3 id="pathexists">pathexists</h3>

- **Purpose:**  
  Checks if a given file path exists.
- **Details:**  
  Returns a boolean indicating whether the file path is valid.

---

<h3 id="emulatedfile-struct">EmulatedFile Struct</h3>

<h3 id="new">new</h3>

- **Purpose:**  
  Creates a new `EmulatedFile` instance, opening a file and initializing its size.
- **Details:**  
  Opens the file with read/write permissions and stores a `Mutex<File>`.

---

<h3 id="new_metadata">new_metadata</h3>

- **Purpose:**  
  Creates an `EmulatedFile` instance by reading the file's metadata.
- **Details:**  
  Retrieves file size and other metadata.

---

<h3 id="close">close</h3>

- **Purpose:**  
  Closes the `EmulatedFile`.
- **Details:**  
  Ensures resources are released after file operations.

---

<h3 id="shrink">shrink</h3>

- **Purpose:**  
  Shrinks the file size to the specified length.
- **Details:**  
  Reduces the file length and updates the `filesize` field.

---

<h3 id="fdatasync">fdatasync</h3>

- **Purpose:**  
  Syncs data to disk without syncing file metadata.
- **Details:**  
  Uses `sync_data()` to ensure file data is written to disk.

---

<h3 id="fsync">fsync</h3>

- **Purpose:**  
  Syncs both file data and metadata to disk.
- **Details:**  
  Ensures full synchronization of file contents.

---

<h3 id="sync_file_range">sync_file_range</h3>

- **Purpose:**  
  Syncs a specified file range to disk.
- **Details:**  
  Allows syncing a portion of the file's data based on offset, bytes, and flags.

---

<h3 id="readat">readat</h3>

- **Purpose:**  
  Reads data from a file at a specified offset.
- **Details:**  
  Populates a C-buffer with data read from the file.

---

<h3 id="writeat">writeat</h3>

- **Purpose:**  
  Writes data to a file at a specified offset.
- **Details:**  
  Takes data from a C-buffer and writes it to the file.

---

<h3 id="readfile_to_new_bytes">readfile_to_new_bytes</h3>

- **Purpose:**  
  Reads the entire file into a byte vector.
- **Details:**  
  Useful for reading a file's full content into memory.

---

<h3 id="writefile_from_bytes">writefile_from_bytes</h3>

- **Purpose:**  
  Writes an entire byte vector to the file.
- **Details:**  
  Replaces the file's content with new data from the byte buffer.

---

<h3 id="zerofill_at">zerofill_at</h3>

- **Purpose:**  
  Writes zeroes to the file starting at a specified offset.
- **Details:**  
  Useful for initializing or overwriting portions of the file with zeros.

---

<h3 id="as_fd_handle_raw_int">as_fd_handle_raw_int</h3>

- **Purpose:**  
  Retrieves the file descriptor as an integer.
- **Details:**  
  Returns the raw file descriptor from the file object.

---

<h3 id="emulatedfilemap-struct">EmulatedFileMap Struct</h3>

<h3 id="new">new</h3>

- **Purpose:**  
  Creates a new `EmulatedFileMap` instance and maps a file into memory.
- **Details:**  
  Maps 1MB of file space and reserves 8 bytes for tracking written data.

---

<h3 id="write_to_map">write_to_map</h3>

- **Purpose:**  
  Writes data to the mapped region of the file.
- **Details:**  
  Automatically extends the mapped memory if the data exceeds the current map size.

---

<h3 id="extend_map">extend_map</h3>

- **Purpose:**  
  Extends the memory-mapped region of the file by 1MB.
- **Details:**  
  Resizes the map when more space is needed for logging or writing.

---

<h3 id="close_emulatedfilemap">close_emulatedfilemap</h3>

- **Purpose:**  
  Closes the memory-mapped file, unmaps the file, and releases resources.
- **Details:**  
  Ensures the file is properly unmapped before closing.

---

<h3 id="mapfilenew">mapfilenew</h3>

- **Purpose:**  
  Creates a new memory-mapped file.
- **Details:**  
  Opens the file and maps 1MB of space, preparing the file for logging or other operations.

---

<h3 id="test-module">Test Module</h3>

<h3 id="test_path_exists_true">test_path_exists_true</h3>

- **Purpose:**  
  Tests whether `pathexists` returns `true` for an existing file.
- **Details:**  
  Uses a temporary file to verify the functionality of `pathexists`.

---

<h3 id="test_path_exists_false">test_path_exists_false</h3>

- **Purpose:**  
  Tests whether `pathexists` returns `false` for a non-existent file.
- **Details:**  
  Verifies that the function behaves as expected when the file does not exist.

---

## File: `misc.rs`

<h3 id="AdvisoryLock Struct">AdvisoryLock Struct</h3>

<h3 id="new">new</h3>

- **Purpose:**  
  Initializes a new `AdvisoryLock` instance.
- **Details:**  
  Creates a new mutex with a guard value of `0` (unlocked state) and a condition variable for managing locks.

---

<h3 id="lock_ex">lock_ex</h3>

- **Purpose:**  
  Acquires an exclusive lock on the mutex.
- **Details:**  
  Waits until the guard value is `0` (unlocked) before setting it to `-1` to indicate that an exclusive lock is held.

---

<h3 id="lock_sh">lock_sh</h3>

- **Purpose:**  
  Acquires a shared lock on the mutex.
- **Details:**  
  Waits until no exclusive lock is held (guard value `>= 0`) and increments the guard value to indicate a shared lock is held.

---

<h3 id="try_lock_ex">try_lock_ex</h3>

- **Purpose:**  
  Attempts to acquire an exclusive lock without blocking.
- **Details:**  
  If the guard value is `0` (unlocked), it sets it to `-1` and returns `true`. Otherwise, it returns `false`.

---

<h3 id="try_lock_sh">try_lock_sh</h3>

- **Purpose:**  
  Attempts to acquire a shared lock without blocking.
- **Details:**  
  If no exclusive lock is held (guard value `>= 0`), it increments the guard value and returns `true`. Otherwise, it returns `false`.

---

<h3 id="unlock">unlock</h3>

- **Purpose:**  
  Releases the lock, whether shared or exclusive.
- **Details:**  
  - If a shared lock is held (guard value `> 0`), it decrements the guard value by 1. If no more shared locks are held (guard value becomes `0`), it notifies a waiting writer.
  - If an exclusive lock is held (guard value `-1`), it sets the guard value to `0` and notifies all waiting readers and writers.

---
## File: `pipe.rs`

<h3 id="new_pipe">new_pipe</h3>

- **Purpose:**  
  Creates a new pipe with the specified buffer size.
- **Details:**  
  Calls `EmulatedPipe::new_with_capacity` to initialize the pipe.

---

<h3 id="emulatedpipe-struct">EmulatedPipe Struct</h3>

<h3 id="new_with_capacity">new_with_capacity</h3>

- **Purpose:**  
  Initializes a new `EmulatedPipe` with a specified buffer size.
- **Details:**  
  Uses a `RingBuffer` to split the buffer into a producer (write end) and consumer (read end).

---

<h3 id="set_eof">set_eof</h3>

- **Purpose:**  
  Marks the pipe as having reached the end-of-file (EOF).
- **Details:**  
  Sets the `eof` flag to `true`, indicating no more data will be written to the pipe.

---

<h3 id="get_write_ref">get_write_ref</h3>

- **Purpose:**  
  Retrieves the current write reference count.
- **Details:**  
  Returns the number of active write references on the pipe.

---

<h3 id="get_read_ref">get_read_ref</h3>

- **Purpose:**  
  Retrieves the current read reference count.
- **Details:**  
  Returns the number of active read references on the pipe.

---

<h3 id="incr_ref">incr_ref</h3>

- **Purpose:**  
  Increments the reference count for either read or write, based on flags.
- **Details:**  
  Increases the reference count depending on whether the pipe is opened for reading (`O_RDONLY`) or writing (`O_WRONLY`).

---

<h3 id="decr_ref">decr_ref</h3>

- **Purpose:**  
  Decrements the reference count for either read or write, based on flags.
- **Details:**  
  Decreases the reference count depending on whether the pipe is closed for reading (`O_RDONLY`) or writing (`O_WRONLY`).

---

<h3 id="check_select_read">check_select_read</h3>

- **Purpose:**  
  Checks whether the pipe is ready for reading.
- **Details:**  
  Returns `true` if the pipe has data to be read or has reached EOF. Otherwise, it returns `false`.

---

<h3 id="check_select_write">check_select_write</h3>

- **Purpose:**  
  Checks whether the pipe is ready for writing.
- **Details:**  
  Returns `true` if there is available space in the pipe's write buffer.

---

<h3 id="write_to_pipe">write_to_pipe</h3>

- **Purpose:**  
  Writes data to the pipe from a provided memory buffer.
- **Details:**  
  Attempts to write `length` bytes into the pipe. If the pipe is full and non-blocking mode is enabled, it returns `EAGAIN`. If all read ends are closed, it returns `EPIPE`.

---

<h3 id="read_from_pipe">read_from_pipe</h3>

- **Purpose:**  
  Reads data from the pipe into a provided memory buffer.
- **Details:**  
  Reads up to `length` bytes. If non-blocking mode is enabled and no data is available, it returns `EAGAIN`. If EOF is reached, it returns `0`.

---

<h3 id="debug-implementation-for-emulatedpipe">Debug Implementation for EmulatedPipe</h3>

- **Purpose:**  
  Provides a custom `Debug` implementation for the `EmulatedPipe` struct.
- **Details:**  
  Displays the read/write reference counts and the EOF status.

---
## File: `types.rs`

<h3 id="fsdata-struct">FSData Struct</h3>

- **Purpose:**  
  Represents filesystem data, including information such as block size, total blocks, and free blocks.
- **Details:**  
  This struct includes fields like `f_bsize` (block size) and `f_blocks` (total number of blocks), among others. It is designed to maintain compatibility with the `stat` and `fstat` system calls.

---

<h3 id="get_fdset">get_fdset</h3>

- **Purpose:**  
  Retrieves a file descriptor set from the union argument.
- **Details:**  
  Converts a raw pointer to an internal `FdSet` and returns a reference to it if valid. Otherwise, returns `None`.

---

<h3 id="get_statdatastruct">get_statdatastruct</h3>

- **Purpose:**  
  Retrieves a `stat` structure from the union argument.
- **Details:**  
  Returns a mutable reference to a `stat` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_fsdatastruct">get_fsdatastruct</h3>

- **Purpose:**  
  Retrieves a `statfs` structure from the union argument.
- **Details:**  
  Returns a mutable reference to a `statfs` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_ioctlptrunion">get_ioctlptrunion</h3>

- **Purpose:**  
  Retrieves an `IoctlPtrUnion` from the union argument.
- **Details:**  
  Returns the `IoctlPtrUnion` without any additional validation.

---

<h3 id="get_ioctl_int">get_ioctl_int</h3>

- **Purpose:**  
  Retrieves an integer from an `IoctlPtrUnion`.
- **Details:**  
  Returns the integer value if the pointer is valid. Otherwise, returns an error indicating an invalid pointer.

---

<h3 id="get_ioctl_char">get_ioctl_char</h3>

- **Purpose:**  
  Retrieves a character (u8) from an `IoctlPtrUnion`.
- **Details:**  
  Returns the character value if the pointer is valid. Otherwise, returns an error indicating an invalid pointer.

---

<h3 id="pack_dirents">pack_dirents</h3>

- **Purpose:**  
  Packs directory entries into a buffer.
- **Details:**  
  Takes a vector of directory entries (`ClippedDirent` structs) and their associated names, and packs them into a buffer pointed to by `baseptr`. It assumes the names are null-terminated and padded to the next 8-byte boundary.

---

<h3 id="get_sockaddr">get_sockaddr</h3>

- **Purpose:**  
  Retrieves a `SockaddrDummy` structure from the union argument.
- **Details:**  
  Returns a mutable reference to a `SockaddrDummy` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_epollevent">get_epollevent</h3>

- **Purpose:**  
  Retrieves an `epoll_event` structure from the union argument.
- **Details:**  
  Returns a mutable reference to an `epoll_event` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_itimerval">get_itimerval</h3>

- **Purpose:**  
  Retrieves an `itimerval` structure from the union argument.
- **Details:**  
  Returns a mutable reference to an `itimerval` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_constitimerval">get_constitimerval</h3>

- **Purpose:**  
  Retrieves a constant `itimerval` structure from the union argument.
- **Details:**  
  Returns a reference to an `itimerval` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_sem">get_sem</h3>

- **Purpose:**  
  Retrieves a `sem_t` structure (semaphore) from the union argument.
- **Details:**  
  Returns a mutable reference to a `sem_t` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

---

<h3 id="get_ifaddrs">get_ifaddrs</h3>

- **Purpose:**  
  Retrieves an `ifaddrs` structure (network interface address) from the union argument.
- **Details:**  
  Returns a mutable reference to an `ifaddrs` structure if the pointer is valid. Otherwise, returns an error indicating an invalid data pointer.

**Comment by Yaxuan-w** [comment]
Removing commented lines under `/interface` folder should be good for now. That would be great if @ChinmayShringi can put a draft on items need to be done here.

**Comment by ChinmayShringi** [comment]
@Yaxuan-w, I have updated the draft for the functions along with a short description of what they did. Please let me know if I missed anything.
