### ISSUE TITLE
Fix select syscall

### ISSUE THREAD

**Issue by qianxichen233** [Lind-Project/RawPOSIX#48]
Currently passing an empty fdset/None to select syscall could cause a panic. The source of the panic comes from 
```
let (writenfd, mut real_writefds) = selectbittables[1].get(&FDKIND_KERNEL).unwrap();
```
in select_syscall of net_calls.rs.
I traced a little bit deeper, and it looks like in ```get_bitmask_for_select```, it will return an empty HashMap if the fdset is empty or None. Then since the HashMap is empty, when it calls get(&FDKIND_KERNEL), that would return None, and the following unwrap would cause panic.

**Comment by JustinCappos** [comment]
Is this using an outdated version of fdtables?   Can you check your code matches the code here: https://github.com/JustinCappos/fdtables/tree/main/docs

**Comment by qianxichen233** [comment]
looks like prepare_bitmasks_for_select and prepare_bitmasks_for_select are the same. My branch just recently merged from porting-fdtables branch so it should be up to date

**Comment by Yaxuan-w** [comment]
This is the latest version of fdtables. I discussed it with Qianxi, and we found that the error is due to incorrect handling of return values, which should be fixed within RawPOSIX. Since these fixes will also affect the implementation in other parts of `select`, I’ve added it to the to-do list and plan to come back with a detailed fix plan in two weeks.

**Comment by JustinCappos** [comment]
Okay, thanks.   I will see if I can get to it beforehand.  If not, I
welcome your patch and would be happy to review.

**Comment by JustinCappos** [comment]
FYI: I added a few minor tests related to empty / blank bitmasks to the
fdtables library.

**Comment by Yaxuan-w** [comment]
This error is fixed by handling null values correctly. Will submit PR for further fix details.

**Comment by Yaxuan-w** [comment]
Fixed: https://github.com/Lind-Project/RawPOSIX/pull/89
