### ISSUE TITLE
Update Test Suite

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/RawPOSIX#7]
Let's add the updated test suite that we updated via RustPOSIX. We can have someone new start working on getting it functional.

**Comment by Yaxuan-w** [comment]
I've synchronized the current progress of the RawPOSIX porting test suite with Justin's repository. Should I merge the current progress into the main branch, or is there another preferred approach? Additionally, would it be feasible to open a new issue to track all the fixes and findings?

**Comment by JustinCappos** [comment]
Make sure you squash and merge as is appropriate.

Justin

**Comment by rennergade** [comment]
> I've synchronized the current progress of the RawPOSIX porting test suite with Justin's repository. Should I merge the current progress into the main branch, or is there another preferred approach? Additionally, would it be feasible to open a new issue to track all the fixes and findings?

I think an issue tracker is a good idea.

As far as this merge we should be able to do it to main. We'll have to look at keeping a stable nacl-branch when we get to Qianxi's PRs.

**Comment by Yaxuan-w** [comment]
Added current documentation issue: https://github.com/Lind-Project/RawPOSIX/issues/15
